$axure.loadCurrentPage({
  "url":"post_status.html",
  "generationDate":new Date(1399599391151.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"MoveSecond"],
  "page":{
    "packageId":"c1d0ecc61a224650bd23752904cde26c",
    "type":"Axure:Page",
    "name":"Post Status",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c39332784b2d4f33b6082816b3a13b59",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"173c27c70ae0418bbbb4b00d9f58d4ab"},
{
          "id":"1482c21113b64570b1388f25d2420cc5",
          "label":"Main",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":144},
            "size":{
              "width":321,
              "height":551}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6250833df4974b3ca53694a1569aeb7b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e767cf0bdab849d6b639f93d5673d883",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":321,
                      "height":551},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDBDBDB}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"975f4d419df34722980fdf38d9c4e1d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":321,
                          "height":551},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDBDBDB}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u4.png"}},
{
                  "id":"22d196b5957a4b98b088ef979699398b",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF727374},
                    "size":{
                      "width":321,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db3242188d7f4db5a5f51730ab17f6cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF727374},
                        "size":{
                          "width":321,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF777777}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/channel/u6.png"}},
{
                  "id":"c139c2fb2cd74650bc72a11bb71f60b4",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":12},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a01332f627b54ec98f5ec3646834a41c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":12},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Post Content in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"post_content.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/status_update/u9.png"}},
{
                  "id":"8c0057339877421d95072bbb53598d41",
                  "label":"Comment Dyn",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":363},
                    "size":{
                      "width":320,
                      "height":188}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"4908c552ff4e40aba305638708321daf",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ea0e867bada84db29a67d0f1e8edd492",
                          "label":"",
                          "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFE9EAE9},
                            "location":{
                              "x":-1,
                              "y":0},
                            "size":{
                              "width":324,
                              "height":188},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5403955bf50e4a88b9d3d6f701e2ffb1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFE9EAE9},
                                "location":{
                                  "x":-1,
                                  "y":0},
                                "size":{
                                  "width":324,
                                  "height":188},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/post_status/u11.png"}},
{
                          "id":"da67581fa4f14c08abebcbb4cddbaa45",
                          "label":"",
                          "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                          "panelIndex":0,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":2,
                              "y":1},
                            "size":{
                              "width":316,
                              "height":188}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"67c22b67573b4e93a37f34a03a1043f7",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":2,
                                  "y":1},
                                "size":{
                                  "width":316,
                                  "height":188}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/status_update_1/u52.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"4ec0e52a2ec54f6e9674c47f3d2f1d65",
                      "label":"State2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"0e4188affd11486898bec5052837860e",
                          "label":"",
                          "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                          "panelIndex":1,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFEFEFEF},
                            "location":{
                              "x":0,
                              "y":186},
                            "size":{
                              "width":321,
                              "height":59},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFD8D8D8}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"eb37e570583a447584865be3f81441cb",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFEFEFEF},
                                "location":{
                                  "x":0,
                                  "y":186},
                                "size":{
                                  "width":321,
                                  "height":59},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFD8D8D8}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/status_update_1/u14.png"}},
{
                          "id":"40525c36e4c04fe1b3045b65c88a9bd7",
                          "label":"Comment Text 1",
                          "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                          "panelIndex":1,
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "fontSize":"12px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF626262,
                              "opacity":1},
                            "location":{
                              "x":40,
                              "y":207},
                            "size":{
                              "width":270,
                              "height":25}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onFocus":{
                              "description":"OnFocus",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Comment Dyn to State1",
                                      "panelsToStates":[{
                                          "panelPath":["8c0057339877421d95072bbb53598d41"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]},
{
                                      "action":"setFocusOnWidget",
                                      "description":"Set Focus on Widget",
                                      "objectPaths":[]},
{
                                      "action":"setPanelState",
                                      "description":"Set Panel to State",
                                      "panelsToStates":[]},
{
                                      "action":"fadeWidget",
                                      "description":"Show/Hide Widget",
                                      "objectsToFades":[]},
{
                                      "action":"setFunction",
                                      "description":"Set text on Unidentified equal to &quot;Comments&quot;",
                                      "expr":{
                                        "exprType":"block",
                                        "subExprs":[]}}]}]}},
                          "tabbable":true},
{
                          "id":"f0304b8294674cc8ae62eb854370d2b7",
                          "label":"Location Services",
                          "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                          "panelIndex":1,
                          "type":"dynamicPanel",
                          "styleType":"dynamicPanel",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":40,
                              "y":190},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "scrollbars":"none",
                          "fitToContent":true,
                          "propagate":false,
                          "diagrams":[{
                              "id":"cae61110f99d441996a5744f475c67a7",
                              "label":"State1",
                              "type":"Axure:PanelDiagram",
                              "objects":[{
                                  "id":"b2070c6682d94d82b5be0c920d3cbcfc",
                                  "label":"Location on text",
                                  "parentDynamicPanel":"f0304b8294674cc8ae62eb854370d2b7",
                                  "panelIndex":0,
                                  "type":"buttonShape",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "fontSize":"9px",
                                    "foreGroundFill":{
                                      "fillType":"solid",
                                      "color":0xFF505050,
                                      "opacity":1},
                                    "location":{
                                      "x":15,
                                      "y":0},
                                    "size":{
                                      "width":97,
                                      "height":12}},
                                  "adaptiveStyles":{
},
                                  "objects":[{
                                      "id":"86871479000c49fc89aa56c48ef42497",
                                      "label":"",
                                      "isContained":true,
                                      "parentDynamicPanel":"f0304b8294674cc8ae62eb854370d2b7",
                                      "panelIndex":0,
                                      "type":"richTextPanel",
                                      "styleType":"paragraph",
                                      "visible":true,
                                      "style":{
                                        "fontSize":"9px",
                                        "foreGroundFill":{
                                          "fillType":"solid",
                                          "color":0xFF505050,
                                          "opacity":1},
                                        "location":{
                                          "x":15,
                                          "y":0},
                                        "size":{
                                          "width":97,
                                          "height":12}},
                                      "adaptiveStyles":{
}}],
                                  "images":{
                                    "normal~":"resources/images/transparent.gif"}},
{
                                  "id":"b1eeb9ae57ce4917a47e24c751c3921e",
                                  "label":"",
                                  "parentDynamicPanel":"f0304b8294674cc8ae62eb854370d2b7",
                                  "panelIndex":0,
                                  "type":"imageBox",
                                  "styleType":"imageBox",
                                  "visible":true,
                                  "style":{
                                    "size":{
                                      "width":11,
                                      "height":12}},
                                  "adaptiveStyles":{
},
                                  "objects":[{
                                      "id":"5da24985e17944d294500daa0607ed88",
                                      "label":"",
                                      "isContained":true,
                                      "parentDynamicPanel":"f0304b8294674cc8ae62eb854370d2b7",
                                      "panelIndex":0,
                                      "type":"richTextPanel",
                                      "styleType":"paragraph",
                                      "visible":true,
                                      "style":{
                                        "size":{
                                          "width":11,
                                          "height":12}},
                                      "adaptiveStyles":{
}}],
                                  "interactionMap":{
                                    "onClick":{
                                      "description":"OnClick",
                                      "cases":[{
                                          "description":"Case 1",
                                          "isNewIfGroup":false,
                                          "actions":[{
                                              "action":"setPanelState",
                                              "description":"Set Location Services to State2",
                                              "panelsToStates":[{
                                                  "panelPath":["f0304b8294674cc8ae62eb854370d2b7"],
                                                  "stateInfo":{
                                                    "setStateType":"diagram",
                                                    "stateNumber":2,
                                                    "stateValue":{
                                                      "exprType":"stringLiteral",
                                                      "value":"1",
                                                      "stos":[]},
                                                    "loop":false,
                                                    "showWhenSet":false,
                                                    "options":{
                                                      "compress":false}}}]}]}]}},
                                  "tabbable":true,
                                  "images":{
                                    "normal~":"images/status_update_1/u20.png"}}],
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "image":null,
                                "imageHorizontalAlignment":"near",
                                "imageVerticalAlignment":"near",
                                "imageRepeat":"auto"},
                              "adaptiveStyles":{
}},
{
                              "id":"1485853c9a294ca494bfd928b7dfe5d8",
                              "label":"State2",
                              "type":"Axure:PanelDiagram",
                              "objects":[{
                                  "id":"e4e261f3a5a04bb3a5b0628609e7954d",
                                  "label":"Location off text",
                                  "parentDynamicPanel":"f0304b8294674cc8ae62eb854370d2b7",
                                  "panelIndex":1,
                                  "type":"buttonShape",
                                  "styleType":"paragraph",
                                  "visible":true,
                                  "style":{
                                    "fontSize":"9px",
                                    "foreGroundFill":{
                                      "fillType":"solid",
                                      "color":0xFF505050,
                                      "opacity":1},
                                    "location":{
                                      "x":15,
                                      "y":0},
                                    "size":{
                                      "width":52,
                                      "height":12}},
                                  "adaptiveStyles":{
},
                                  "objects":[{
                                      "id":"0dd663626c5a42c3b4ca4cb705131b73",
                                      "label":"",
                                      "isContained":true,
                                      "parentDynamicPanel":"f0304b8294674cc8ae62eb854370d2b7",
                                      "panelIndex":1,
                                      "type":"richTextPanel",
                                      "styleType":"paragraph",
                                      "visible":true,
                                      "style":{
                                        "fontSize":"9px",
                                        "foreGroundFill":{
                                          "fillType":"solid",
                                          "color":0xFF505050,
                                          "opacity":1},
                                        "location":{
                                          "x":15,
                                          "y":0},
                                        "size":{
                                          "width":52,
                                          "height":12}},
                                      "adaptiveStyles":{
}}],
                                  "images":{
                                    "normal~":"resources/images/transparent.gif"}},
{
                                  "id":"c9b8f3b29b974817995602a30c087be1",
                                  "label":"",
                                  "parentDynamicPanel":"f0304b8294674cc8ae62eb854370d2b7",
                                  "panelIndex":1,
                                  "type":"imageBox",
                                  "styleType":"imageBox",
                                  "visible":true,
                                  "style":{
                                    "size":{
                                      "width":11,
                                      "height":12}},
                                  "adaptiveStyles":{
},
                                  "objects":[{
                                      "id":"88abe006a6934ea9a186e65cd30c1dcf",
                                      "label":"",
                                      "isContained":true,
                                      "parentDynamicPanel":"f0304b8294674cc8ae62eb854370d2b7",
                                      "panelIndex":1,
                                      "type":"richTextPanel",
                                      "styleType":"paragraph",
                                      "visible":true,
                                      "style":{
                                        "size":{
                                          "width":11,
                                          "height":12}},
                                      "adaptiveStyles":{
}}],
                                  "interactionMap":{
                                    "onClick":{
                                      "description":"OnClick",
                                      "cases":[{
                                          "description":"Case 1",
                                          "isNewIfGroup":false,
                                          "actions":[{
                                              "action":"setPanelState",
                                              "description":"Set Location Services to State1",
                                              "panelsToStates":[{
                                                  "panelPath":["f0304b8294674cc8ae62eb854370d2b7"],
                                                  "stateInfo":{
                                                    "setStateType":"diagram",
                                                    "stateNumber":1,
                                                    "stateValue":{
                                                      "exprType":"stringLiteral",
                                                      "value":"1",
                                                      "stos":[]},
                                                    "loop":false,
                                                    "showWhenSet":false,
                                                    "options":{
                                                      "compress":false}}}]}]}]}},
                                  "tabbable":true,
                                  "images":{
                                    "normal~":"images/status_update_1/u24.png"}}],
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF},
                                "image":null,
                                "imageHorizontalAlignment":"near",
                                "imageVerticalAlignment":"near",
                                "imageRepeat":"auto"},
                              "adaptiveStyles":{
}}]},
{
                          "id":"7dceef0e4f4c4f87ad1843159b82905f",
                          "label":"",
                          "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                          "panelIndex":1,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC},
                            "location":{
                              "x":9,
                              "y":207},
                            "size":{
                              "width":26,
                              "height":25},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"dc7dd9ba523743278481f9dcecc453f5",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFCCCCCC},
                                "location":{
                                  "x":9,
                                  "y":207},
                                "size":{
                                  "width":26,
                                  "height":25},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/status_update_1/u26.png"}},
{
                          "id":"9ed936b7ec82481eb6de21ccbeba074b",
                          "label":"",
                          "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                          "panelIndex":1,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":17,
                              "y":214},
                            "size":{
                              "width":10,
                              "height":10},
                            "cornerRadiusTopLeft":"100"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a8dd497843754901b595ec65f557fbf4",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":17,
                                  "y":214},
                                "size":{
                                  "width":10,
                                  "height":10},
                                "cornerRadiusTopLeft":"100"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/status_update_1/u28.png"}},
{
                          "id":"b0fcc5620f98461d8e9b04783ba1ea0c",
                          "label":"",
                          "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                          "panelIndex":1,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF333333,
                              "opacity":1},
                            "location":{
                              "x":14,
                              "y":222},
                            "size":{
                              "width":16,
                              "height":8},
                            "rotation":"0",
                            "textRotation":"0",
                            "borderWidth":"0",
                            "cornerRadiusTopLeft":"0"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"225d730fa6d44e9aa5ac6ba546e2acff",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8c0057339877421d95072bbb53598d41",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF333333,
                                  "opacity":1},
                                "location":{
                                  "x":14,
                                  "y":222},
                                "size":{
                                  "width":16,
                                  "height":8},
                                "rotation":"0",
                                "textRotation":"0",
                                "borderWidth":"0",
                                "cornerRadiusTopLeft":"0"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/status_update_1/u30.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"ead65894ef1d417185524653606ffe0f",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":10,
                      "y":63},
                    "size":{
                      "width":26,
                      "height":25},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a1931d2ce1148efb00480a60c0b8432",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":10,
                          "y":63},
                        "size":{
                          "width":26,
                          "height":25},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/status_update_1/u26.png"}},
{
                  "id":"a7b73310dbec4280be8c648b05ca29b1",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":70},
                    "size":{
                      "width":10,
                      "height":10},
                    "cornerRadiusTopLeft":"100"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"452620e8e4fb49bd900cca14b1ab794c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":70},
                        "size":{
                          "width":10,
                          "height":10},
                        "cornerRadiusTopLeft":"100"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/status_update_1/u28.png"}},
{
                  "id":"69beeabe7bfe4bea95c32c11a6a43428",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":15,
                      "y":78},
                    "size":{
                      "width":16,
                      "height":8},
                    "rotation":"0",
                    "textRotation":"0",
                    "borderWidth":"0",
                    "cornerRadiusTopLeft":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45e4c7c6828640579a720eaf4eb96cb3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":15,
                          "y":78},
                        "size":{
                          "width":16,
                          "height":8},
                        "rotation":"0",
                        "textRotation":"0",
                        "borderWidth":"0",
                        "cornerRadiusTopLeft":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/status_update_1/u30.png"}},
{
                  "id":"2402f83d9d5344299af68680dcb9313c",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF4F5F3},
                    "location":{
                      "x":41,
                      "y":63},
                    "size":{
                      "width":269,
                      "height":287},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8c397e1590c4febbd2fcd60848ffe9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF4F5F3},
                        "location":{
                          "x":41,
                          "y":63},
                        "size":{
                          "width":269,
                          "height":287},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/post_status/u39.png"}},
{
                  "id":"f3e10573179841aa83679e9cdb8817f8",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Bold', 'Arial'",
                    "fontSize":"12px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF7C8081,
                      "opacity":1},
                    "location":{
                      "x":10,
                      "y":45},
                    "size":{
                      "width":64,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06d0a73f3b65473f83786090630b6513",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Bold', 'Arial'",
                        "fontSize":"12px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF7C8081,
                          "opacity":1},
                        "location":{
                          "x":10,
                          "y":45},
                        "size":{
                          "width":64,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"62c5a242e671419f869cbdfdd6b9867f",
                  "label":"Location Services",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":328},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"1e4125ce3ff44059876993fbc61fe4d4",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"cc415be102fa4b33be2a9158ffb9a6cc",
                          "label":"Location on text",
                          "parentDynamicPanel":"62c5a242e671419f869cbdfdd6b9867f",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"9px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF505050,
                              "opacity":1},
                            "location":{
                              "x":15,
                              "y":0},
                            "size":{
                              "width":97,
                              "height":12}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"cacfab94c7cb4bd1923daae8b7b9738a",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"62c5a242e671419f869cbdfdd6b9867f",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"9px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF505050,
                                  "opacity":1},
                                "location":{
                                  "x":15,
                                  "y":0},
                                "size":{
                                  "width":97,
                                  "height":12}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"62508d6996984fc1bc0f20e36e89b03f",
                          "label":"",
                          "parentDynamicPanel":"62c5a242e671419f869cbdfdd6b9867f",
                          "panelIndex":0,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":11,
                              "height":12}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"bd1860f443294dfa8814a13e2af302b8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"62c5a242e671419f869cbdfdd6b9867f",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":11,
                                  "height":12}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Location Services to State2",
                                      "panelsToStates":[{
                                          "panelPath":["62c5a242e671419f869cbdfdd6b9867f"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":2,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/status_update_1/u20.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"97fe004efa88455dbbef92ed4d56ccc9",
                      "label":"State2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"16c3a1ed188844e398a6685c674332cf",
                          "label":"Location off text",
                          "parentDynamicPanel":"62c5a242e671419f869cbdfdd6b9867f",
                          "panelIndex":1,
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"9px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF505050,
                              "opacity":1},
                            "location":{
                              "x":15,
                              "y":0},
                            "size":{
                              "width":52,
                              "height":12}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1fe89ed29a9f48bbb4e0b71a9c67d976",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"62c5a242e671419f869cbdfdd6b9867f",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"9px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF505050,
                                  "opacity":1},
                                "location":{
                                  "x":15,
                                  "y":0},
                                "size":{
                                  "width":52,
                                  "height":12}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"7fa99e84be2c4c42bcfd9cc78f311a90",
                          "label":"",
                          "parentDynamicPanel":"62c5a242e671419f869cbdfdd6b9867f",
                          "panelIndex":1,
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":11,
                              "height":12}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"3cc3a86e3cd0417aa989ddb36fd94da6",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"62c5a242e671419f869cbdfdd6b9867f",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":11,
                                  "height":12}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"Case 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"Set Location Services to State1",
                                      "panelsToStates":[{
                                          "panelPath":["62c5a242e671419f869cbdfdd6b9867f"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/status_update_1/u24.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"4745a64386af4f9cad1c456193974715",
                  "label":"",
                  "parentDynamicPanel":"1482c21113b64570b1388f25d2420cc5",
                  "panelIndex":0,
                  "type":"textArea",
                  "styleType":"textArea",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF4F5F3},
                    "location":{
                      "x":51,
                      "y":71},
                    "size":{
                      "width":249,
                      "height":247}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set text on This equal to &quot;&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":true,
                                        "isFocused":false,
                                        "isTarget":false},
{
                                        "exprType":"stringLiteral",
                                        "value":"",
                                        "stos":[]}]}]}}]}]}}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "173c27c70ae0418bbbb4b00d9f58d4ab":{
      "packageId":"173c27c70ae0418bbbb4b00d9f58d4ab",
      "type":"Axure:Master",
      "name":"iPhone",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c60c636099a44626bbd4a83a30e1a155",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":379,
                "height":797}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97a5ab8834f540a1bb37a576e6d418c0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":379,
                    "height":797}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/splash_screen/u1.png"}}]}}},
  "objectPaths":{
    "c39332784b2d4f33b6082816b3a13b59":{
      "scriptId":"u0",
      "c60c636099a44626bbd4a83a30e1a155":{
        "scriptId":"u1"},
      "97a5ab8834f540a1bb37a576e6d418c0":{
        "scriptId":"u2"}},
    "1482c21113b64570b1388f25d2420cc5":{
      "scriptId":"u3"},
    "e767cf0bdab849d6b639f93d5673d883":{
      "scriptId":"u4"},
    "975f4d419df34722980fdf38d9c4e1d3":{
      "scriptId":"u5"},
    "22d196b5957a4b98b088ef979699398b":{
      "scriptId":"u6"},
    "db3242188d7f4db5a5f51730ab17f6cf":{
      "scriptId":"u7"},
    "c139c2fb2cd74650bc72a11bb71f60b4":{
      "scriptId":"u8"},
    "a01332f627b54ec98f5ec3646834a41c":{
      "scriptId":"u9"},
    "8c0057339877421d95072bbb53598d41":{
      "scriptId":"u10"},
    "ea0e867bada84db29a67d0f1e8edd492":{
      "scriptId":"u11"},
    "5403955bf50e4a88b9d3d6f701e2ffb1":{
      "scriptId":"u12"},
    "da67581fa4f14c08abebcbb4cddbaa45":{
      "scriptId":"u13"},
    "67c22b67573b4e93a37f34a03a1043f7":{
      "scriptId":"u14"},
    "0e4188affd11486898bec5052837860e":{
      "scriptId":"u15"},
    "eb37e570583a447584865be3f81441cb":{
      "scriptId":"u16"},
    "40525c36e4c04fe1b3045b65c88a9bd7":{
      "scriptId":"u17"},
    "f0304b8294674cc8ae62eb854370d2b7":{
      "scriptId":"u18"},
    "b2070c6682d94d82b5be0c920d3cbcfc":{
      "scriptId":"u19"},
    "86871479000c49fc89aa56c48ef42497":{
      "scriptId":"u20"},
    "b1eeb9ae57ce4917a47e24c751c3921e":{
      "scriptId":"u21"},
    "5da24985e17944d294500daa0607ed88":{
      "scriptId":"u22"},
    "e4e261f3a5a04bb3a5b0628609e7954d":{
      "scriptId":"u23"},
    "0dd663626c5a42c3b4ca4cb705131b73":{
      "scriptId":"u24"},
    "c9b8f3b29b974817995602a30c087be1":{
      "scriptId":"u25"},
    "88abe006a6934ea9a186e65cd30c1dcf":{
      "scriptId":"u26"},
    "7dceef0e4f4c4f87ad1843159b82905f":{
      "scriptId":"u27"},
    "dc7dd9ba523743278481f9dcecc453f5":{
      "scriptId":"u28"},
    "9ed936b7ec82481eb6de21ccbeba074b":{
      "scriptId":"u29"},
    "a8dd497843754901b595ec65f557fbf4":{
      "scriptId":"u30"},
    "b0fcc5620f98461d8e9b04783ba1ea0c":{
      "scriptId":"u31"},
    "225d730fa6d44e9aa5ac6ba546e2acff":{
      "scriptId":"u32"},
    "ead65894ef1d417185524653606ffe0f":{
      "scriptId":"u33"},
    "9a1931d2ce1148efb00480a60c0b8432":{
      "scriptId":"u34"},
    "a7b73310dbec4280be8c648b05ca29b1":{
      "scriptId":"u35"},
    "452620e8e4fb49bd900cca14b1ab794c":{
      "scriptId":"u36"},
    "69beeabe7bfe4bea95c32c11a6a43428":{
      "scriptId":"u37"},
    "45e4c7c6828640579a720eaf4eb96cb3":{
      "scriptId":"u38"},
    "2402f83d9d5344299af68680dcb9313c":{
      "scriptId":"u39"},
    "a8c397e1590c4febbd2fcd60848ffe9a":{
      "scriptId":"u40"},
    "f3e10573179841aa83679e9cdb8817f8":{
      "scriptId":"u41"},
    "06d0a73f3b65473f83786090630b6513":{
      "scriptId":"u42"},
    "62c5a242e671419f869cbdfdd6b9867f":{
      "scriptId":"u43"},
    "cc415be102fa4b33be2a9158ffb9a6cc":{
      "scriptId":"u44"},
    "cacfab94c7cb4bd1923daae8b7b9738a":{
      "scriptId":"u45"},
    "62508d6996984fc1bc0f20e36e89b03f":{
      "scriptId":"u46"},
    "bd1860f443294dfa8814a13e2af302b8":{
      "scriptId":"u47"},
    "16c3a1ed188844e398a6685c674332cf":{
      "scriptId":"u48"},
    "1fe89ed29a9f48bbb4e0b71a9c67d976":{
      "scriptId":"u49"},
    "7fa99e84be2c4c42bcfd9cc78f311a90":{
      "scriptId":"u50"},
    "3cc3a86e3cd0417aa989ddb36fd94da6":{
      "scriptId":"u51"},
    "4745a64386af4f9cad1c456193974715":{
      "scriptId":"u52"}}});