$axure.loadCurrentPage({
  "url":"voicemail.html",
  "generationDate":new Date(1401332714324.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0a7483fc359d478f93854e740e90ce74",
    "type":"Axure:Page",
    "name":"Voicemail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"557bff6700b1437285670d4ddb861165",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x7CFF0000},
            "location":{
              "x":673,
              "y":287},
            "size":{
              "width":68,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a342f9fe74d442b957f29cd46715038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x7CFF0000},
                "location":{
                  "x":673,
                  "y":287},
                "size":{
                  "width":68,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/voicemail/u0.png"}},
{
          "id":"fe03c16d8ddb4a95acb106e965426b42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1},
            "size":{
              "width":974,
              "height":398},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea39dcc9f8564930ad2af4bdf47bea61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1},
                "size":{
                  "width":974,
                  "height":398},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/voicemail/u2.png"}},
{
          "id":"be280fc5204e45ab9ffa6b3d42c45eaa",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":341},
            "size":{
              "width":960,
              "height":80}},
          "adaptiveStyles":{
},
          "masterId":"91a6c3504cb24ea680adb104047b8110"},
{
          "id":"c1ceee31b64543a58b9a83a46137e8f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x68000000},
            "location":{
              "x":0,
              "y":182},
            "size":{
              "width":313,
              "height":159}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47833a37a7644979ac305d29a368e4b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x68000000},
                "location":{
                  "x":0,
                  "y":182},
                "size":{
                  "width":313,
                  "height":159}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dialpad/u164.png"}},
{
          "id":"63c3507c9f9c443fa22a4c41a8e0f963",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF272727},
            "location":{
              "x":0,
              "y":180},
            "size":{
              "width":313,
              "height":29},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15300c9a5ed6482e855df334f58cdadc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF272727},
                "location":{
                  "x":0,
                  "y":180},
                "size":{
                  "width":313,
                  "height":29},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dialpad/u166.png"}},
{
          "id":"258b849a14324963b20161dd1e88081d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":188},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5607aa85ee34b868790ec3f4c08782a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":188},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/bottom_bar/u137.png"}},
{
          "id":"17289fec74af46fd8fbac09a8b5a9102",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":188},
            "size":{
              "width":87,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca1bb868aae541eab904a6e5e522abd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":188},
                "size":{
                  "width":87,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"658fef49b71b4d1aaf1cf3ce603786db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":187},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc7a28484a0e4c4795f797047cc8b095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":187},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dialpad/u49.png"}},
{
          "id":"671c3a3230034bf4b5b8a3b30df22386",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":108,
              "y":188},
            "size":{
              "width":87,
              "height":15},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a00c09a48fd04737803e091d218fc85e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":188},
                "size":{
                  "width":87,
                  "height":15},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f4fe1c0798141068169d5f90ca04aae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7C5C5C5C},
            "location":{
              "x":248,
              "y":182},
            "size":{
              "width":28,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc09f5e7611a45d995bb818d5019a2d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7C5C5C5C},
                "location":{
                  "x":248,
                  "y":182},
                "size":{
                  "width":28,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/incoming_call_interaction/u36.png"}},
{
          "id":"9635869fa330467e97ec23b5e71e4fec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":188},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dadcecfa5e9f4160ab19da65c8e80363",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":188},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/incoming_call_interaction/u38.png"}},
{
          "id":"8453cdfab38f4c51b33e1316da554b07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xA8FFFFFF},
            "location":{
              "x":0,
              "y":210},
            "size":{
              "width":313,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bea89303b454615b4e5c8af7f8e4c50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xA8FFFFFF},
                "location":{
                  "x":0,
                  "y":210},
                "size":{
                  "width":313,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dialpad/u174.png"}},
{
          "id":"0f83cc09379941fe9ed6afb13b09f882",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"bold",
            "location":{
              "x":79,
              "y":218},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da0ecbcb7c40476da2d0a7e8415ad705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"bold",
                "location":{
                  "x":79,
                  "y":218},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b9592aebd79493b90b36237843d0c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"bold",
            "location":{
              "x":79,
              "y":243},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45dd7fcb23b34859bdf0186237ed43e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"bold",
                "location":{
                  "x":79,
                  "y":243},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35cab9aa17e243ab8d395ecc5db48a4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"bold",
            "location":{
              "x":79,
              "y":268},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c11d8da592a74816b1a06998e340192a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"bold",
                "location":{
                  "x":79,
                  "y":268},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aaaef6885a34f4faed61a9f383dfaee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"bold",
            "location":{
              "x":79,
              "y":293},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e222ebdaaf145739caaec368fd052e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"bold",
                "location":{
                  "x":79,
                  "y":293},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9a001e0dda04ee0b4b452091fc74655",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"11px",
            "fontWeight":"bold",
            "location":{
              "x":79,
              "y":318},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94316c22d1804cfe82aa635aa59fd5fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"11px",
                "fontWeight":"bold",
                "location":{
                  "x":79,
                  "y":318},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e00f6a1229e84d2c8b832ea15ea88d25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":167,
              "y":218},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17db7856b24b4157a01c73cf96d90d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":167,
                  "y":218},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"890657e1e4a947de879909135f69f65a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":167,
              "y":243},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62a1e1a7d3784e5eae2a5fb454962c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":167,
                  "y":243},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41c83a1de8ae42f6990660cb10a0cef6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":167,
              "y":268},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6553e5e916646b48e07198d39959aa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":167,
                  "y":268},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2ba88ac8b38419d9dccb3ad58c248f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "underline":true,
            "location":{
              "x":167,
              "y":293},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33df7178b8034b19b2dbc172099ddc1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "underline":true,
                "location":{
                  "x":167,
                  "y":293},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa15d415970248ceb293e5e3d05a9165",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "underline":true,
            "location":{
              "x":167,
              "y":318},
            "size":{
              "width":91,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e85bcc88b40b49f1b677928bb66c2a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "underline":true,
                "location":{
                  "x":167,
                  "y":318},
                "size":{
                  "width":91,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e4ba588b8ae40c7a02fa4e2a9decd7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF00},
            "location":{
              "x":348,
              "y":182},
            "size":{
              "width":279,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0854f7c37ed84c5d8f848cfa5cb3cf37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00},
                "location":{
                  "x":348,
                  "y":182},
                "size":{
                  "width":279,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/voicemail/u85.png"}},
{
          "id":"e201dee4487144889b77a144d8e1403c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":190},
            "size":{
              "width":27,
              "height":27},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3caaa6ec109417896dfa07c30aea057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":356,
                  "y":190},
                "size":{
                  "width":27,
                  "height":27},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/voicemail/u87.png"}},
{
          "id":"178906fd7d0348bd89be482f864d65ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":195},
            "size":{
              "width":233,
              "height":48},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc6fd62129d6499682e4d69d6afc37aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":195},
                "size":{
                  "width":233,
                  "height":48},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6b11ec58dcb4c24b9c7b809462a3444",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7C5C5C5C},
            "location":{
              "x":216,
              "y":181},
            "size":{
              "width":28,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e99b0e4f0294de6bb74cdae0a4efcbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7C5C5C5C},
                "location":{
                  "x":216,
                  "y":181},
                "size":{
                  "width":28,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/incoming_call_interaction/u16.png"}},
{
          "id":"67daf428071e4d2fb37bbff157195491",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":222,
              "y":187},
            "size":{
              "width":16,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d56c6cf22924229981e7eea93fd6902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":222,
                  "y":187},
                "size":{
                  "width":16,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/voicemail/u93.png"}},
{
          "id":"339802d4a39b476abd00b378d3771c9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":219},
            "size":{
              "width":48,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e1859f9280847609be6f83ccc85e672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":219},
                "size":{
                  "width":48,
                  "height":48},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/voicemail/u95.png"}}]}},
  "masters":{
    "91a6c3504cb24ea680adb104047b8110":{
      "packageId":"91a6c3504cb24ea680adb104047b8110",
      "type":"Axure:Master",
      "name":"Bottom Bar",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c89b4031199b4a76a7db5e3e608e956c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF272727},
              "location":{
                "x":0,
                "y":207},
              "size":{
                "width":960,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"916e6a7bc98b4388be4dbd0995e66427",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF272727},
                  "location":{
                    "x":0,
                    "y":207},
                  "size":{
                    "width":960,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u10.png"}},
{
            "id":"489dcc6c0969474aa95de0304d2193d2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF313131},
              "location":{
                "x":10,
                "y":207},
              "size":{
                "width":303,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF666666}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8d15cd837eec494692142ac458c2a218",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF313131},
                  "location":{
                    "x":10,
                    "y":207},
                  "size":{
                    "width":303,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF666666}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u12.png"}},
{
            "id":"1be7569e46df4dac9a8422f8e3f44070",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x44797979},
              "location":{
                "x":17,
                "y":207},
              "size":{
                "width":65,
                "height":58},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"366a83245b674c0a999a775163c3bd49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x44797979},
                  "location":{
                    "x":17,
                    "y":207},
                  "size":{
                    "width":65,
                    "height":58},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u14.png"}},
{
            "id":"7a1a0050f76248e49dd088bb8c9f69ea",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":24,
                "y":216},
              "size":{
                "width":32,
                "height":32},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92e605c689254bd680fd83a2ece87a88",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":24,
                    "y":216},
                  "size":{
                    "width":32,
                    "height":32},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u16.png"}},
{
            "id":"e0dd908ede29410d93a44079423815a2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":98,
                "y":224},
              "size":{
                "width":45,
                "height":45},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cadb7cad7a84403da6f2c41a988457fa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":98,
                    "y":224},
                  "size":{
                    "width":45,
                    "height":45},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u18.png"}},
{
            "id":"54c03d8a5a6d49c4baba45713af88713",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":891,
                "y":212},
              "size":{
                "width":45,
                "height":45},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6d661b560e33449f8d46ae646390bf64",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":891,
                    "y":212},
                  "size":{
                    "width":45,
                    "height":45},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u20.png"}},
{
            "id":"53d5626ea5474063a19bf3497c95a44c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":172,
                "y":224},
              "size":{
                "width":45,
                "height":45},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"de396a4ff80a4ea99d899cc90626c20d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":172,
                    "y":224},
                  "size":{
                    "width":45,
                    "height":45},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u22.png"}},
{
            "id":"e5d8eb9111e24e76bfc8f657ec15d37a",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":246,
                "y":224},
              "size":{
                "width":45,
                "height":45},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e05f6b4235d45cd802d362cd07ea1e1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":246,
                    "y":224},
                  "size":{
                    "width":45,
                    "height":45},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u24.png"}},
{
            "id":"07dd6634210147228c0c7481157b6558",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x44797979},
              "location":{
                "x":314,
                "y":263},
              "size":{
                "width":646,
                "height":23},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9018d3c69f884b68a3c426b1e39f62e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x44797979},
                  "location":{
                    "x":314,
                    "y":263},
                  "size":{
                    "width":646,
                    "height":23},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u26.png"}},
{
            "id":"597d3c40d8864cc6ab514f9c9ecd7e62",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":318,
                "y":268},
              "size":{
                "width":16,
                "height":16},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3e0f96cf5c3431398065fa444dfbafd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":318,
                    "y":268},
                  "size":{
                    "width":16,
                    "height":16},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u28.png"}},
{
            "id":"8a406025f8934537aa2f6a78b57bbc5d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontSize":"11px",
              "fontWeight":"bold",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFE8E8E8,
                "opacity":1},
              "location":{
                "x":341,
                "y":269},
              "size":{
                "width":150,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4ab1725acc65479ab11dfbcf35d37cd5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontSize":"11px",
                  "fontWeight":"bold",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFE8E8E8,
                    "opacity":1},
                  "location":{
                    "x":341,
                    "y":269},
                  "size":{
                    "width":150,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"da9735770b5e4d1abfbfef6cb04eacfd",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":437,
                "y":267},
              "size":{
                "width":16,
                "height":16},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"98d1779209fd4695a552e4897310bd97",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":437,
                    "y":267},
                  "size":{
                    "width":16,
                    "height":16},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u32.png"}},
{
            "id":"9d8b90cc9d3546a8b4b9c6e07420e8be",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontSize":"11px",
              "fontWeight":"bold",
              "location":{
                "x":457,
                "y":268},
              "size":{
                "width":484,
                "height":14},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"412dd625961e4857baefd9a81249bdc2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontSize":"11px",
                  "fontWeight":"bold",
                  "location":{
                    "x":457,
                    "y":268},
                  "size":{
                    "width":484,
                    "height":14},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"045f5a20f0be4b0d97471b27e2b593ec",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":63,
                "y":211},
              "size":{
                "width":16,
                "height":16},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b96db3a5ead5416fa62bb4f7c6ed890d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":63,
                    "y":211},
                  "size":{
                    "width":16,
                    "height":16},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u36.png"}},
{
            "id":"b51d1d5e94b94c169d5516017a9ecb93",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xE0FFFFFF},
              "location":{
                "x":17,
                "y":266},
              "size":{
                "width":65,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad702983b17f414e91628d42f4962d6b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xE0FFFFFF},
                  "location":{
                    "x":17,
                    "y":266},
                  "size":{
                    "width":65,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u38.png"}},
{
            "id":"6635340a2bb54b6f85d90255bdee04fa",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF2A2B2B,
                "opacity":1},
              "location":{
                "x":19,
                "y":267},
              "size":{
                "width":70,
                "height":18},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ad66eb07098d4d3db35ed4cfe444fb33",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF2A2B2B,
                    "opacity":1},
                  "location":{
                    "x":19,
                    "y":267},
                  "size":{
                    "width":70,
                    "height":18},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f286bb8d3e5d4270b06c8be7b27a472c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontSize":"10px",
              "fontWeight":"bold",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":19,
                "y":252},
              "size":{
                "width":70,
                "height":13},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0d86f0a5725c4e97a1a6e0b439f7fe5e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontSize":"10px",
                  "fontWeight":"bold",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":19,
                    "y":252},
                  "size":{
                    "width":70,
                    "height":13},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"471744a8a241422aa2ee65c0c6cb3f08",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF00FF00},
              "location":{
                "x":944,
                "y":219},
              "size":{
                "width":8,
                "height":8},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF00FF00},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"10a78ae2e5294a94b8bd3acf09a10b81",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF00FF00},
                  "location":{
                    "x":944,
                    "y":219},
                  "size":{
                    "width":8,
                    "height":8},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF00FF00},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u44.png"}},
{
            "id":"84aaaec5c81144a0a1c638d549ec8655",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":944,
                "y":242},
              "size":{
                "width":8,
                "height":8},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e3d0b819819b4abebc23b16e475b957a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":944,
                    "y":242},
                  "size":{
                    "width":8,
                    "height":8},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u46.png"}},
{
            "id":"2e24e9a474ce490bb2327674fbefa5f7",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":866,
                "y":215},
              "size":{
                "width":16,
                "height":16},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"12a35b31b5574c87a17184cf2de32f50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":866,
                    "y":215},
                  "size":{
                    "width":16,
                    "height":16},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u48.png"}},
{
            "id":"300dfed8fb344ee9937505da0ef6bc99",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":866,
                "y":239},
              "size":{
                "width":16,
                "height":16},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF000000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3637f0534b354b388e749976efecdf45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":866,
                    "y":239},
                  "size":{
                    "width":16,
                    "height":16},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF000000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/bottom_bar/u50.png"}}]}}},
  "objectPaths":{
    "557bff6700b1437285670d4ddb861165":{
      "scriptId":"u0"},
    "4a342f9fe74d442b957f29cd46715038":{
      "scriptId":"u1"},
    "fe03c16d8ddb4a95acb106e965426b42":{
      "scriptId":"u2"},
    "ea39dcc9f8564930ad2af4bdf47bea61":{
      "scriptId":"u3"},
    "be280fc5204e45ab9ffa6b3d42c45eaa":{
      "scriptId":"u4",
      "c89b4031199b4a76a7db5e3e608e956c":{
        "scriptId":"u5"},
      "916e6a7bc98b4388be4dbd0995e66427":{
        "scriptId":"u6"},
      "489dcc6c0969474aa95de0304d2193d2":{
        "scriptId":"u7"},
      "8d15cd837eec494692142ac458c2a218":{
        "scriptId":"u8"},
      "1be7569e46df4dac9a8422f8e3f44070":{
        "scriptId":"u9"},
      "366a83245b674c0a999a775163c3bd49":{
        "scriptId":"u10"},
      "7a1a0050f76248e49dd088bb8c9f69ea":{
        "scriptId":"u11"},
      "92e605c689254bd680fd83a2ece87a88":{
        "scriptId":"u12"},
      "e0dd908ede29410d93a44079423815a2":{
        "scriptId":"u13"},
      "cadb7cad7a84403da6f2c41a988457fa":{
        "scriptId":"u14"},
      "54c03d8a5a6d49c4baba45713af88713":{
        "scriptId":"u15"},
      "6d661b560e33449f8d46ae646390bf64":{
        "scriptId":"u16"},
      "53d5626ea5474063a19bf3497c95a44c":{
        "scriptId":"u17"},
      "de396a4ff80a4ea99d899cc90626c20d":{
        "scriptId":"u18"},
      "e5d8eb9111e24e76bfc8f657ec15d37a":{
        "scriptId":"u19"},
      "9e05f6b4235d45cd802d362cd07ea1e1":{
        "scriptId":"u20"},
      "07dd6634210147228c0c7481157b6558":{
        "scriptId":"u21"},
      "9018d3c69f884b68a3c426b1e39f62e7":{
        "scriptId":"u22"},
      "597d3c40d8864cc6ab514f9c9ecd7e62":{
        "scriptId":"u23"},
      "e3e0f96cf5c3431398065fa444dfbafd":{
        "scriptId":"u24"},
      "8a406025f8934537aa2f6a78b57bbc5d":{
        "scriptId":"u25"},
      "4ab1725acc65479ab11dfbcf35d37cd5":{
        "scriptId":"u26"},
      "da9735770b5e4d1abfbfef6cb04eacfd":{
        "scriptId":"u27"},
      "98d1779209fd4695a552e4897310bd97":{
        "scriptId":"u28"},
      "9d8b90cc9d3546a8b4b9c6e07420e8be":{
        "scriptId":"u29"},
      "412dd625961e4857baefd9a81249bdc2":{
        "scriptId":"u30"},
      "045f5a20f0be4b0d97471b27e2b593ec":{
        "scriptId":"u31"},
      "b96db3a5ead5416fa62bb4f7c6ed890d":{
        "scriptId":"u32"},
      "b51d1d5e94b94c169d5516017a9ecb93":{
        "scriptId":"u33"},
      "ad702983b17f414e91628d42f4962d6b":{
        "scriptId":"u34"},
      "6635340a2bb54b6f85d90255bdee04fa":{
        "scriptId":"u35"},
      "ad66eb07098d4d3db35ed4cfe444fb33":{
        "scriptId":"u36"},
      "f286bb8d3e5d4270b06c8be7b27a472c":{
        "scriptId":"u37"},
      "0d86f0a5725c4e97a1a6e0b439f7fe5e":{
        "scriptId":"u38"},
      "471744a8a241422aa2ee65c0c6cb3f08":{
        "scriptId":"u39"},
      "10a78ae2e5294a94b8bd3acf09a10b81":{
        "scriptId":"u40"},
      "84aaaec5c81144a0a1c638d549ec8655":{
        "scriptId":"u41"},
      "e3d0b819819b4abebc23b16e475b957a":{
        "scriptId":"u42"},
      "2e24e9a474ce490bb2327674fbefa5f7":{
        "scriptId":"u43"},
      "12a35b31b5574c87a17184cf2de32f50":{
        "scriptId":"u44"},
      "300dfed8fb344ee9937505da0ef6bc99":{
        "scriptId":"u45"},
      "3637f0534b354b388e749976efecdf45":{
        "scriptId":"u46"}},
    "c1ceee31b64543a58b9a83a46137e8f2":{
      "scriptId":"u47"},
    "47833a37a7644979ac305d29a368e4b9":{
      "scriptId":"u48"},
    "63c3507c9f9c443fa22a4c41a8e0f963":{
      "scriptId":"u49"},
    "15300c9a5ed6482e855df334f58cdadc":{
      "scriptId":"u50"},
    "258b849a14324963b20161dd1e88081d":{
      "scriptId":"u51"},
    "d5607aa85ee34b868790ec3f4c08782a":{
      "scriptId":"u52"},
    "17289fec74af46fd8fbac09a8b5a9102":{
      "scriptId":"u53"},
    "ca1bb868aae541eab904a6e5e522abd1":{
      "scriptId":"u54"},
    "658fef49b71b4d1aaf1cf3ce603786db":{
      "scriptId":"u55"},
    "dc7a28484a0e4c4795f797047cc8b095":{
      "scriptId":"u56"},
    "671c3a3230034bf4b5b8a3b30df22386":{
      "scriptId":"u57"},
    "a00c09a48fd04737803e091d218fc85e":{
      "scriptId":"u58"},
    "2f4fe1c0798141068169d5f90ca04aae":{
      "scriptId":"u59"},
    "cc09f5e7611a45d995bb818d5019a2d4":{
      "scriptId":"u60"},
    "9635869fa330467e97ec23b5e71e4fec":{
      "scriptId":"u61"},
    "dadcecfa5e9f4160ab19da65c8e80363":{
      "scriptId":"u62"},
    "8453cdfab38f4c51b33e1316da554b07":{
      "scriptId":"u63"},
    "3bea89303b454615b4e5c8af7f8e4c50":{
      "scriptId":"u64"},
    "0f83cc09379941fe9ed6afb13b09f882":{
      "scriptId":"u65"},
    "da0ecbcb7c40476da2d0a7e8415ad705":{
      "scriptId":"u66"},
    "4b9592aebd79493b90b36237843d0c8e":{
      "scriptId":"u67"},
    "45dd7fcb23b34859bdf0186237ed43e6":{
      "scriptId":"u68"},
    "35cab9aa17e243ab8d395ecc5db48a4c":{
      "scriptId":"u69"},
    "c11d8da592a74816b1a06998e340192a":{
      "scriptId":"u70"},
    "6aaaef6885a34f4faed61a9f383dfaee":{
      "scriptId":"u71"},
    "3e222ebdaaf145739caaec368fd052e0":{
      "scriptId":"u72"},
    "b9a001e0dda04ee0b4b452091fc74655":{
      "scriptId":"u73"},
    "94316c22d1804cfe82aa635aa59fd5fd":{
      "scriptId":"u74"},
    "e00f6a1229e84d2c8b832ea15ea88d25":{
      "scriptId":"u75"},
    "17db7856b24b4157a01c73cf96d90d2f":{
      "scriptId":"u76"},
    "890657e1e4a947de879909135f69f65a":{
      "scriptId":"u77"},
    "62a1e1a7d3784e5eae2a5fb454962c0d":{
      "scriptId":"u78"},
    "41c83a1de8ae42f6990660cb10a0cef6":{
      "scriptId":"u79"},
    "e6553e5e916646b48e07198d39959aa2":{
      "scriptId":"u80"},
    "d2ba88ac8b38419d9dccb3ad58c248f8":{
      "scriptId":"u81"},
    "33df7178b8034b19b2dbc172099ddc1d":{
      "scriptId":"u82"},
    "fa15d415970248ceb293e5e3d05a9165":{
      "scriptId":"u83"},
    "e85bcc88b40b49f1b677928bb66c2a9f":{
      "scriptId":"u84"},
    "8e4ba588b8ae40c7a02fa4e2a9decd7d":{
      "scriptId":"u85"},
    "0854f7c37ed84c5d8f848cfa5cb3cf37":{
      "scriptId":"u86"},
    "e201dee4487144889b77a144d8e1403c":{
      "scriptId":"u87"},
    "c3caaa6ec109417896dfa07c30aea057":{
      "scriptId":"u88"},
    "178906fd7d0348bd89be482f864d65ff":{
      "scriptId":"u89"},
    "cc6fd62129d6499682e4d69d6afc37aa":{
      "scriptId":"u90"},
    "a6b11ec58dcb4c24b9c7b809462a3444":{
      "scriptId":"u91"},
    "0e99b0e4f0294de6bb74cdae0a4efcbf":{
      "scriptId":"u92"},
    "67daf428071e4d2fb37bbff157195491":{
      "scriptId":"u93"},
    "5d56c6cf22924229981e7eea93fd6902":{
      "scriptId":"u94"},
    "339802d4a39b476abd00b378d3771c9b":{
      "scriptId":"u95"},
    "9e1859f9280847609be6f83ccc85e672":{
      "scriptId":"u96"}}});